### PR TITLE
Laravel 9.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 9.x.

**Before merging**, you need to:

- Checkout the `l9-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: The latest version of Laravel has a dependency for `phpunit/phpunit` of `^9.3`. If you would like to also upgrade your tests, you may run the [PHPUnit 9 Shift](https://laravelshift.com/upgrade-phpunit-9) for free.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/workos-php.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "workos/workos-php": "dev-l9-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by jasonmccreary** [comment]
@adamzinder, it seems odd both this and the `workos-php-laravel` package require `illuminate/support`. I think a better approach would be only the "Laravel" package would have that dependency. The separation would prevent the current dual release needed to support new versions of Laravel.

**Comment by sheldonvaughn** [comment]
> @adamzinder, it seems odd both this and the `workos-php-laravel` package require `illuminate/support`. I think a better approach would be only the "Laravel" package would have that dependency. The separation would prevent the current dual release needed to support new versions of Laravel.

Thanks Jason, we'll merge the changes from this PR (everything looks good) and then evaluate dropping the illuminate/support package from workos-php in a different PR. Appreciate the feedback!

**Review by sheldonvaughn — APPROVED** [review]

**Comment by jasonmccreary** [comment]
@sheldonvaughn, looks like this got reverted.

You may want to also look at your order or parameters. Optional parameters before required parameters was deprecated in PHP 8.

> PHP Deprecated:  Required parameter $state follows optional parameter $domain in lib/SSO.php on line 26

**Comment by sheldonvaughn** [comment]
> @sheldonvaughn, looks like this got reverted.
> 
> You may want to also look at your order or parameters. Optional parameters before required parameters was deprecated in PHP 8.
> 
> > PHP Deprecated:  Required parameter $state follows optional parameter $domain in lib/SSO.php on line 26

Hi Jason - thanks for reaching out. That's correct, this PR failed our unit tests, so it has been reverted. Working on these changes today and noticed the same thing along with a few others that will need to be updated.

**Pull request merged**
